---
- name: Validaciones y administración básica en Linux
  hosts: os_linux
  become: true
  gather_facts: true
 
  tasks:
    - name: Verificar uso de CPU
      ansible.builtin.shell: "top -bn1 | grep 'Cpu(s)' | awk '{print 100 - $8}'"
      register: cpu_uso
      changed_when: false
 
    - name: Mostrar uso de CPU
      ansible.builtin.debug:
        msg: "Uso de CPU en {{ inventory_hostname }}: {{ cpu_uso.stdout }}%"
 
    - name: Obtener servicios del sistema
      ansible.builtin.service_facts:
 
    - name: Enlistar servicios y estado
      ansible.builtin.debug:
        msg: "{{ item.key }} -> {{ item.value.state }}"
      loop: "{{ ansible_facts.services | dict2items }}"
 
    - name: Crear usuario ecuador
      ansible.builtin.user:
        name: ecuador
        state: present
        create_home: true
        shell: /bin/bash
 
    - name: Actualizar sistema operativo en Debian/Ubuntu
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
      when: ansible_facts['os_family'] == "Debian"
 
    - name: Actualizar sistema operativo en RedHat/Rocky/AlmaLinux/CentOS
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_only: true
      when: ansible_facts['os_family'] == "RedHat"
 