---
- name: Obtener uso de CPU en Windows (usando módulo)
  hosts: all
  gather_facts: false
 
  tasks:
    - name: Obtener CPU con WMIC
      ansible.windows.win_command: >
        wmic cpu get loadpercentage
      register: cpu_output
 
    - name: Limpiar salida
      set_fact:
        cpu_percent: "{{ cpu_output.stdout_lines[1] | trim }}"
 
    - name: Mostrar uso de CPU
      ansible.builtin.debug:
        msg: "Uso de CPU en {{ inventory_hostname }}: {{ cpu_percent }}%"
    

    - name: Validar estado de un servicio en Windows
      ansible.windows.win_service_info:
        name: "{{ servicio }}"
      register: resultado_servicio
    
    - name: Validar que el servicio esté corriendo
      ansible.builtin.assert:
        that:
          - resultado_servicio.services | length > 0
          - resultado_servicio.services[0].state == "running"
        fail_msg: "El servicio {{ servicio }} NO está corriendo o no existe"
        success_msg: "El servicio {{ servicio }} está corriendo correctamente"
    