---
- name: Obtener uso de CPU en Windows (usando módulo)
  hosts: windows
  gather_facts: false
 
  tasks:
    - name: Obtener CPU con WMIC
      ansible.windows.win_command: >
        wmic cpu get loadpercentage
      register: cpu_output
 
    - name: Limpiar salida
      set_fact:
        cpu_percent: "{{ cpu_output.stdout_lines[1] | trim }}"
 
    - name: Mostrar uso de CPU
      ansible.builtin.debug:
        msg: "Uso de CPU en {{ inventory_hostname }}: {{ cpu_percent }}%"