---
- name: Obtener uso de CPU en Windows (usando módulo)
  hosts: all
  gather_facts: false
 
  tasks:
    - name: Obtener CPU con WMIC
      ansible.windows.win_command: >
        wmic cpu get loadpercentage
      register: cpu_output
 
    - name: Limpiar salida
      set_fact:
        cpu_percent: "{{ cpu_output.stdout_lines[1] | trim }}"
 
    - name: Mostrar uso de CPU
      ansible.builtin.debug:
        msg: "Uso de CPU en {{ inventory_hostname }}: {{ cpu_percent }}%"
    

    - name: Validar estado de un servicio en Windows
      ansible.windows.win_service_info:
        name: Spooler   # cambia por el servicio que necesites
      register: service_info
    
    - name: Mostrar estado del servicio
      ansible.builtin.debug:
        msg: "El servicio Spooler está: {{ service_info.services[0].state }}"